package ollie;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;

/**
 * Displays one user or Ollie message with a speaker label.
 */
public class DialogBox extends VBox {
    private static final double USER_MESSAGE_WIDTH_RATIO = 0.78;
    private static final String ERROR_STYLE_CLASS = "error-dialog";
    private static final String OLLIE_STYLE_CLASS = "ollie-dialog";
    private static final String USER_STYLE_CLASS = "user-dialog";

    @FXML
    private Label messageLabel;
    @FXML
    private Label speakerLabel;

    private DialogBox(String text, String speaker, String styleClass) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(
                    DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load the dialog box layout.", e);
        }

        messageLabel.setText(text);
        speakerLabel.setText(speaker);
        messageLabel.setMinWidth(0.0);
        getStyleClass().add(styleClass);
    }

    /**
     * Creates a right-aligned dialog for a user message.
     *
     * @param text Message entered by the user.
     * @return User dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "", USER_STYLE_CLASS);
        dialogBox.showAsUserMessage();
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialog for an Ollie response.
     *
     * @param text Response generated by Ollie.
     * @return Ollie dialog box.
     */
    public static DialogBox getOllieDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, UI.SPEAKER_NAME, OLLIE_STYLE_CLASS);
        dialogBox.showAsOllieMessage();
        return dialogBox;
    }

    /**
     * Creates a visually highlighted dialog for an error response.
     *
     * @param text Error response generated by Ollie.
     * @return Error dialog box.
     */
    public static DialogBox getErrorDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "OLLIE / ALERT", ERROR_STYLE_CLASS);
        dialogBox.showAsOllieMessage();
        return dialogBox;
    }

    private void showAsUserMessage() {
        speakerLabel.setManaged(false);
        speakerLabel.setVisible(false);
        messageLabel.maxWidthProperty().bind(widthProperty().multiply(USER_MESSAGE_WIDTH_RATIO));
        setAlignment(Pos.TOP_RIGHT);
    }

    private void showAsOllieMessage() {
        messageLabel.setMaxWidth(Double.MAX_VALUE);
        setAlignment(Pos.TOP_LEFT);
    }
}
