package ollie;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Displays one user or Ollie message with a speaker label.
 */
public class DialogBox extends HBox {
    private static final String OLLIE_STYLE_CLASS = "ollie-dialog";
    private static final String USER_STYLE_CLASS = "user-dialog";

    @FXML
    private Label messageLabel;
    @FXML
    private Label speakerLabel;

    private DialogBox(String text, String speaker, String styleClass) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(
                    DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load the dialog box layout.", e);
        }

        messageLabel.setText(text);
        speakerLabel.setText(speaker);
        getStyleClass().add(styleClass);
    }

    /**
     * Creates a right-aligned dialog for a user message.
     *
     * @param text Message entered by the user.
     * @return User dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, "You", USER_STYLE_CLASS);
    }

    /**
     * Creates a left-aligned dialog for an Ollie response.
     *
     * @param text Response generated by Ollie.
     * @return Ollie dialog box.
     */
    public static DialogBox getOllieDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "Ollie", OLLIE_STYLE_CLASS);
        dialogBox.flip();
        return dialogBox;
    }

    /**
     * Moves the speaker label to the left for an Ollie response.
     */
    private void flip() {
        getChildren().setAll(speakerLabel, messageLabel);
        setAlignment(Pos.TOP_LEFT);
    }
}
